{{- /* set root with the value of "." as the "." is override inside the range loop */}}
{{- $root := . }}

{{- range $peerOrg := $root.Values.peerOrgs}}

{{- /* shared variables */}}
{{- $clusterName := $root.Values.clusterName}}
{{- $orgName :=  $peerOrg.name }}
{{- $orgDomainName := $peerOrg.domain }}
{{- $stateDbType := $peerOrg.stateDbType }}
{{- $namespace := $clusterName }}
{{- $sharedPVCName := printf "%s-shared" $peerOrg.domain }}
{{- $cliPVCName := printf "%s-cli" $peerOrg.domain }}


# the deployment of cli
{{- $name := printf "cli-%s" $orgName }}
{{- $scope := dict "name" $name "namespace" $namespace "orgName" $orgName "orgDomainName" $orgDomainName "sharedPVC" $sharedPVCName "cliPVC" $cliPVCName "hostAliases" $root.Values.hostAliases }}
{{- template "cli.deployment" $scope }}

##################################################################
# peers
{{- range $index := until ($peerOrg.template.count | int) }}
# the deployment of peer
{{- $name := printf "peer%d" $index }}
{{- $scope := dict "name" $name "namespace" $namespace "orgName" $orgName "orgDomainName" $orgDomainName "stateDbType" $stateDbType "pvc" $sharedPVCName "hostAliases" $root.Values.hostAliases }}
{{- template "peer.deployment" $scope }}

# the service of peer
{{- $name := printf "peer%d" $index }}
{{- $scope := dict "name" $name "namespace" $namespace "orgDomainName" $orgDomainName "orgName" $orgName }}
{{- template "peer.service" $scope }}

# the ingress of peer
{{- $name := printf "%s-peer%d" $orgName $index }}
{{- $path := printf "/fabric/%s/%s/%s" $clusterName $orgName $name }}
{{- $scope := dict "name" $name "namespace" $namespace "path" $path "backendServiceName" $name "backendServicePort" "7051" }}
{{- template "ingress" $scope }}

{{- end }}
###################################################################

# the deployment of explorer db
{{- $name := printf "pgsql-%s" $orgName }}
{{- $scope := dict "name" $name "namespace" $namespace "orgName" $orgName "orgDomainName" $orgDomainName "pvc" $sharedPVCName "hostAliases" $root.Values.hostAliases }}
{{- template "explorer.db.deployment" $scope }}

# the service of explorer db
{{- $name := printf "pgsql-%s" $orgName }}
{{- $scope := dict "name" $name "namespace" $namespace "orgDomainName" $orgDomainName "orgName" $orgName }}
{{- template "explorer.db.service" $scope }}

# the deployment of explorer app
{{- $name := printf "explorer-%s" $orgName }}
{{- $dbHostName := printf "pgsql-%s" $orgName }}
{{- $scope := dict "name" $name "dbHostName" $dbHostName "namespace" $namespace "orgName" $orgName "orgDomainName" $orgDomainName "pvc" $sharedPVCName "hostAliases" $root.Values.hostAliases }}
{{- template "explorer.app.deployment" $scope }}

# the service of explorer app
{{- $name := printf "explorer-%s" $orgName }}
{{- $dbHostName := printf "pgsql-%s" $orgName }}
{{- $scope := dict "name" $name "dbHostName" $dbHostName "namespace" $namespace "orgDomainName" $orgDomainName "orgName" $orgName }}
{{- template "explorer.app.service" $scope }}

{{- end }}